### ISSUE TITLE
Name of submodule in generated Open API client package is mismatching with the sample script  

### ISSUE THREAD

**Issue by sergeiRomanovRO** [yahoojp-marketing/ads-search-api-python-samples#19]
The current verison of the sample script is mismatching the module name:

I have replicated all of the steps in documentation and after running this command I got an error:
```
python report_sample.py
```
I got an error
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], [line 2](vscode-notebook-cell:?execution_count=3&line=2)
      [1](vscode-notebook-cell:?execution_count=3&line=1) from openapi_client.api.report_definition_service_api import ReportDefinitionServiceApi
----> [2](vscode-notebook-cell:?execution_count=3&line=2) from openapi_client.model.report_definition import ReportDefinition
      [3](vscode-notebook-cell:?execution_count=3&line=3) from openapi_client.model.report_definition_service_download_selector import ReportDefinitionServiceDownloadSelector
      [4](vscode-notebook-cell:?execution_count=3&line=4) from openapi_client.model.report_definition_service_operation import ReportDefinitionServiceOperation

ModuleNotFoundError: No module named 'openapi_client.model'
```

I noticed that the package generated from the current file uses `models` instead of `model`. Maybe it is good idea to change it also in the sample.

**Comment by xshoji** [comment]
@sergeiRomanovRO 
Could you please check your openapi-generator version? This sample script specifically requires the openapi-generator version *6.1.0* for proper functionality. Just for your information, it appears that the openapi-generator version 7.5.0 generates the package name as 'models'.

**Comment by sergeiRomanovRO** [comment]
Thanks for pointing this out! I was indeed using the latest version, so it resulted in different module names.
