### ISSUE TITLE
Possibility of incremental report retrieval 

### ISSUE THREAD

**Issue by sergeiRomanovRO** [yahoojp-marketing/ads-search-api-python-samples#20]
Hello here! 

I have been working on the report retrieval from Yahoo Search platform, and have been stuck for a while. Currenlty I try to define a report which would retrieve data from a particular period of time beeing segemted by day. My current report definition looks like this: 

``` python
report_definition = ReportDefinition(
        report_date_range_type=ReportDefinitionServiceReportDateRangeType('CUSTOM_DATE'),
        dateRange = ReportDefinitionServiceReportDateRange(
            endDate="20231231",
            startDate="20230101",
        ),
        report_name="sample",       
        fields=["ACCOUNT_ID","ACCOUNT_NAME", "IMPS","CLICKS","CONVERSIONS", "COST", ],
        report_type=ReportDefinitionServiceReportType('ACCOUNT'),
        report_language=ReportDefinitionServiceReportLanguage("EN"),
    )

```

However, it retrieves summarised date over the provided time. Thus, my question: is there a way to define a report or a single API call the way it will retrieve a report with the segments of metrics per day? Or the only possible strategy here is to define a report per day, which though seems quite not optimal for the system? 

Thanks in advance!

**Comment by xshoji** [comment]
@sergeiRomanovRO 

Thank you for your inquiry. 

> Thus, my question: is there a way to define a report or a single API call the way it will retrieve a report with the segments of metrics per day?

ReportDefinitionService offers the "DAY" field to support a report with the segments of metrics per day.
If you have more any questions about a specification of Yahoo! JAPAN Ads API, please inquire at the following URL:
https://ads-developers.yahoo.co.jp/en/ads-api/faq/

**Comment by sergeiRomanovRO** [comment]
Thanks a lot for you input! It have saved a lot of time and development struggle😄. I wasn't quite self evident how to set this, but I wasn't also looking at the FAQ page, but rather the API documentation it self.
