### ISSUE TITLE
open_api download

### ISSUE THREAD

**Issue by davamini** [yahoojp-marketing/ads-search-api-python-samples#5]
I noticed that if I use the latest open_api version (5.0.1 as of now) the package downloads incorrectly and cannot be used after running setup.py. 

It seems that the open_api version must be 4.2.3 to download the package correctly.

**Comment by xshoji** [comment]
@davamini 
Thank you for your feedback.
Sample codes in this repository does not conform to the latest openapi-generator.
As you pointed out, openapi-generator version must be 4.2.3 to run this sample code.
This requirements will be added in README.md.
